name: Deploy to AWS Environments with OIDC and Snyk IaC

on:
  push:
    branches: 
      - main
      - development
  
  pull_request:
    branches:
      - main
      - development

jobs:

  Plan_to_sec_development:
    if: github.ref == 'refs/heads/development'
    uses: thecornelisinc/github_action/.github/workflows/aws_tf_plan.yml@development
    with:
      # path: 'sec'
      environment: 'sec'
      aws_region: 'us-east-1'
      aws_role_to_assume: 'arn:aws:iam::863980140052:role/sec_github_action' 
    permissions:
      id-token: write  # Required for OIDC
      contents: read

  Deploy_to_sec_main:
    if: github.ref == 'refs/heads/main'
    uses: thecornelisinc/github_action/.github/workflows/aws_tf_apply.yml@main
    with:
      # path: 'sec'
      environment: 'sec'
      aws_region: 'us-east-1'
      aws_role_to_assume: 'arn:aws:iam::863980140052:role/sec_github_action' 
    permissions:
      id-token: write  # Required for OIDC
      contents: read