name: Deploy to AWS Environments with OIDC and Snyk IaC

on:
  push:
    branches: 
      - main
  
  pull_request:
    branches:
      - main

jobs:

  Deploy_to_sec_main:
    uses: thecornelisinc/github_action/.github/workflows/apply.yml@main
    with:
      account: sec
      aws_region: 'us-east-1'
      aws_role_to_assume: 'arn:aws:iam::863980140052:role/sec_github_action' 
    permissions:
      id-token: write  # Required for OIDC
      contents: read