name: Deploy to AWS Environments with OIDC and Snyk IaC

on:
  push:
    branches: 
      - main
  
  pull_request:
    branches:
      - main

jobs:

  Deploy_to_sec_main:
    uses: thecornelisinc/shared_repo/.github/workflows/apply.yml@main
    with:
      account: sec
      aws_region: 'us-east-1'
      aws_role_to_assume: $arn-of-assume-role
    permissions:
      id-token: write  # Required for OIDC
      contents: read
    secrets:
      snyk_token: ${{ secrets.SNYK_TOKEN }}
